#!/usr/bin/env node
'use strict';

// Auto-generated search CLI for DmeMeta in DME context
// Generated by graphForge providerGenerator v1.0
// This script reads Neo4j connection info from the DME search config

const path = require('path');
const os = require('os');
const configFileProcessor = require('qtools-config-file-processor');
const commandLineParser = require('qtools-parse-command-line');
const commandLineParameters = commandLineParser.getParameters();

const { graphSearchTool } = require('qtools-graph-forge-core');

const GRAPH_NAME = 'DmeMeta';

// Load DME config to get connection info
const hostname = os.hostname();
const configName = (hostname === 'qMini.local' || hostname === 'qbook.local') ? 'instanceSpecific/qbook' : '';
const findProjectRoot = ({ rootFolderName = 'system', closest = true } = {}) =>
	__dirname.replace(new RegExp(`^(.*${closest ? '' : '?'}\/${rootFolderName}).*$`), '$1');
const projectRoot = findProjectRoot({ closest: false });
const configDirPath = projectRoot + '/configs/' + configName + '/';

let boltUri, neo4jPassword;
try {
	const dmeConfig = configFileProcessor.getConfig('dataModelExplorerSearch.ini', configDirPath, { resolve: true });
	const section = dmeConfig.dataModelExplorerSearch || dmeConfig;
	boltUri = section.neo4jBoltUri || 'bolt://localhost:7706';
	neo4jPassword = section.neo4jPassword || '';
} catch (err) {
	console.error('Cannot find dataModelExplorerSearch.ini. Set connection via --boltUri and --password.');
	process.exit(1);
}

// Create embedder — config baked in at generation time
const { embeddingClient } = require('qtools-graph-forge-core');
const embedder = embeddingClient.create({
	provider: 'voyage',
	model: 'voyage-4',
	dimension: 1024,
	apiKey: 'pa-3W7FFeGKVZ4xEN9Lh2ceXMATTpbLbK-b2nwg6TbqF3o',
	batchSize: 20
});

const switches = commandLineParameters.switches || {};
const values = commandLineParameters.values || {};
const fileList = commandLineParameters.fileList || [];
const getVal = (key) => { const arr = values[key]; return (Array.isArray(arr) && arr.length > 0) ? arr[0] : undefined; };

boltUri = getVal('boltUri') || boltUri;
neo4jPassword = getVal('password') || neo4jPassword;

if (switches.search || getVal('query')) {
	graphSearchTool.search({
		boltUri, password: neo4jPassword, embedder,
		query: getVal('query') || fileList[0],
		graphName: GRAPH_NAME, limit: parseInt(getVal('limit') || '10', 10)
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else if (switches.stats) {
	graphSearchTool.stats({
		boltUri, password: neo4jPassword, graphName: GRAPH_NAME
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else if (switches.rawCypher) {
	graphSearchTool.rawCypher({
		boltUri, password: neo4jPassword, query: getVal('query') || fileList[0]
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else if (switches.explore) {
	graphSearchTool.explore({
		boltUri, password: neo4jPassword,
		name: getVal('name') || fileList[0], graphName: GRAPH_NAME
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else if (switches.history) {
	graphSearchTool.history({
		boltUri, password: neo4jPassword,
		limit: parseInt(getVal('limit') || '50', 10)
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else {
	console.log('Usage: dme_metaSearch -search --query="..." | -stats | -rawCypher --query="CYPHER" | -explore --name="..." | -history');
}
