#!/usr/bin/env node
'use strict';

// Auto-generated search CLI for EdMatrix in DME context
// Generated by graphForge providerGenerator v1.0
// This script reads Neo4j connection info from the DME search config

const path = require('path');
const os = require('os');
const configFileProcessor = require('qtools-config-file-processor');
const commandLineParser = require('qtools-parse-command-line');
const commandLineParameters = commandLineParser.getParameters();

const graphSearchTool = require(path.join('/Users/tqwhite/Documents/webdev/graphForge/system/code/cli/lib.d/graph-forge-core/lib', 'graphSearchTool'));

const GRAPH_NAME = 'EdMatrix';

// Load DME config to get connection info
const hostname = os.hostname();
const configName = (hostname === 'qMini.local' || hostname === 'qbook.local') ? 'instanceSpecific/qbook' : '';
const findProjectRoot = ({ rootFolderName = 'system', closest = true } = {}) =>
	__dirname.replace(new RegExp(`^(.*${closest ? '' : '?'}\/${rootFolderName}).*$`), '$1');
const projectRoot = findProjectRoot({ closest: false });
const configDirPath = projectRoot + '/configs/' + configName + '/';

let boltUri, neo4jPassword, voyageApiKey;
try {
	const dmeConfig = configFileProcessor.getConfig('dataModelExplorerSearch.ini', configDirPath, { resolve: true });
	const section = dmeConfig.dataModelExplorerSearch || dmeConfig;
	boltUri = section.neo4jBoltUri || 'bolt://localhost:7706';
	neo4jPassword = section.neo4jPassword || '';
	voyageApiKey = section.voyageApiKey || '';
} catch (err) {
	// Fallback to graphForge config
	try {
		const gfConfig = configFileProcessor.getConfig('graphForge.ini', '/Users/tqwhite/Documents/webdev/graphForge/configs/instanceSpecific/qbook/', { resolve: true });
		boltUri = 'bolt://localhost:7706';
		neo4jPassword = '99d0615d205eead0ea65b3f642ffb3d5';
		voyageApiKey = (gfConfig.graphForge || {}).voyageApiKey || '';
	} catch (e) {
		console.error('Cannot find config. Set connection via --boltUri and --password.');
		process.exit(1);
	}
}

const switches = commandLineParameters.switches || {};
const values = commandLineParameters.values || {};
const fileList = commandLineParameters.fileList || [];
const getVal = (key) => { const arr = values[key]; return (Array.isArray(arr) && arr.length > 0) ? arr[0] : undefined; };

boltUri = getVal('boltUri') || boltUri;
neo4jPassword = getVal('password') || neo4jPassword;

if (switches.search || getVal('query')) {
	graphSearchTool.search({
		boltUri, password: neo4jPassword, voyageApiKey,
		query: getVal('query') || fileList[0],
		graphName: GRAPH_NAME, limit: parseInt(getVal('limit') || '10', 10)
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else if (switches.stats) {
	graphSearchTool.stats({
		boltUri, password: neo4jPassword, graphName: GRAPH_NAME
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else if (switches.rawCypher) {
	graphSearchTool.rawCypher({
		boltUri, password: neo4jPassword, query: getVal('query') || fileList[0]
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else if (switches.explore) {
	graphSearchTool.explore({
		boltUri, password: neo4jPassword,
		name: getVal('name') || fileList[0], graphName: GRAPH_NAME
	}, (e, r) => { if (e) { console.error(e); process.exit(1); } console.log(JSON.stringify(r, null, 2)); });
} else {
	console.log('Usage: edmatrixSearch -search --query="..." | -stats | -rawCypher --query="CYPHER" | -explore --name="..."');
}
